// Write a multithreaded program that generates the Fibonacci series. The program should 
// work as follows: The user will enter on the command line the number of Fibonacci numbers 
// that the program is to generate. The program then will create a separate thread that will 
// generate the Fibonacci numbers, placing the sequence in data that is shared by the threads 
// (an array is probably the most convenient data structure). When the thread finishes 
// execution the parent will output the sequence generated by the child thread. Because the 
// parent thread cannot begin outputting the Fibonacci sequence until the child thread finishes, 
// this will require having the parent thread wait for the child thread to finish. 
#include <pthread.h>
#include <stdio.h>

int fib[100];

void* child_thread(void * param){
    int *id = (int *)param;
    fib[0] = 0;
    fib[1] = 1;
    for(int j=2;j<*id;j++)
        fib[j] = fib[j-1] + fib[j-2];
}
int main(){
    pthread_t thread;
    int i;
    printf("Enter number of fibbonaci sequence : ");
    scanf("%d", &i);
    pthread_create(&thread, 0, &child_thread, (void*)&i);
    pthread_join(thread,0);
    printf("Fibonacci sequence generated - \n");
    for(int j=0;j<i;j++){
        printf("%d ", fib[j]);
    }
    printf("\n");
}